version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: project_name_mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ../../var/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: unless-stopped
    env_file: .env
    networks:
      related_product_network:
        aliases:
          - mysql

  nginx:
    image: nginx:latest
    container_name: project_name_nginx
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - ../..:/var/www
      - ../config/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    links:
      - php
    restart: unless-stopped
    networks:
      related_product_network:
        aliases:
          - nginx

  php:
    image: kazar-project_name/php:7-fpm
    container_name: project_name_php
    working_dir: /var/www
    env_file: .env
    volumes:
      - ../..:/var/www
    restart: unless-stopped
    networks:
      related_product_network:
        aliases:
          - php

networks:
  related_product_network:
    driver: bridge
